# Data Preprocessing Tools

## Importing the libraries

In [62]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [63]:
df = pd.read_csv('Data.csv')
X = df.iloc[:, :-1].values         # : means within the range, so takes all the rows, then using -1 means we take all the rows except the last one
y = df.iloc[:, -1].values            

#iloc is used to index the columns, .loc is used by label
#values used to return the values of the columns inside the numpy arrays. How X and y become numpy arrays

In [64]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [65]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [66]:
df.isna().sum()
#used to count the number of missing vaues per column

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

Imputer by scikit-learn fills in a statistics of the column for misssing values in the column. Could be mean (standard), median, mode, etc..

In [67]:
from sklearn.impute import SimpleImputer
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(X[:,1:])
X[:,1:] = imr.transform(X[:,1:])

In [68]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

ColumnTransformer is used to apply a function to a column

OneHotEncoder is to encode numerical categorical values into a one-hot numeric vector (a binary column for each category)

In [69]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
#use OneHotEncoder and apply it to the indexes of the columns chosen
X = np.array(ct.fit_transform(X))

In [70]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

LabelEncoder converts the text into numerical class values

In [71]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [72]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [74]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [75]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [76]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [77]:
print(y_test)

[0 1]


## Feature Scaling

Used to normalize the range of the data so that no observation prevails over the other. Should be done after the train_test_split because it grabs information on the test set, which you are not supposed to have before training is done. 

In [78]:
from sklearn.preprocessing import StandardScaler    #recommended over normal
sc = StandardScaler()
#x- mean(x)/std(x)
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])       #scales the values after the one-hot encoded values
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [79]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [80]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
